/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cj_mix_SignalCatch */

#ifndef _Included_com_cj_mix_SignalCatch
#define _Included_com_cj_mix_SignalCatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cj_mix_SignalCatch
 * Method:    init
 * Signature: (Lcom/cj/mix/SignalCatch/SignalCB;)V
 */
JNIEXPORT void JNICALL Java_com_cj_mix_SignalCatch_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cj_mix_SignalCatch
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cj_mix_SignalCatch_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
