/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cj_mix_SignalCatch_SignalCB */

#ifndef _Included_com_cj_mix_SignalCatch_SignalCB
#define _Included_com_cj_mix_SignalCatch_SignalCB
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
